version: 2

install_elixir: &install_elixir
  run:
    name: Install Elixir
    command: |
      wget https://repo.hex.pm/builds/elixir/v${ELIXIR_VERSION}.zip
      unzip -d /usr/local/elixir v${ELIXIR_VERSION}.zip
      echo 'export PATH=/usr/local/elixir/bin:$PATH' >> $BASH_ENV

install_hex_rebar: &install_hex_rebar
  run:
    name: Install hex and rebar
    command: |
      mix local.hex --force
      mix local.rebar --force

install_system_deps: &install_system_deps
  run:
    name: Install system dependencies
    command: |
      apt update
      apt install -y unzip libmnl-dev libnl-genl-3-dev

install_nerves_bootstrap: &install_nerves_bootstrap
  run:
    name: Install nerves_bootstrap
    command: |
      cd /tmp
      mix archive.install hex nerves_bootstrap "~> 1.0" --force

install_mdl: &install_mdl
  run:
    name: Install Markdown Lint
    command: |
      apt install -y ruby
      gem install mdl

defaults: &defaults
  working_directory: ~/repo

jobs:
  build_elixir_1_9_otp_22:
    docker:
      - image: erlang:22.0
        environment:
          ELIXIR_VERSION: 1.9.1-otp-22
          LC_ALL: C.UTF-8
    <<: *defaults
    steps:
      - checkout
      - <<: *install_system_deps
      - <<: *install_mdl
      - <<: *install_elixir
      - <<: *install_hex_rebar
      - restore_cache:
          keys:
            - v1-mix-cache-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - run: MIX_ENV=test mix coveralls.circle
      - run: mix format --check-formatted
      - run: mdl --style .circleci/md-style.rb *.md
      - run: MIX_ENV=docs mix docs
      - run: mix hex.build
      - run: mix dialyzer --halt-exit-status
      - save_cache:
          key: v1-mix-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps

  build_elixir_1_8_otp_22:
    docker:
      - image: erlang:22.0
        environment:
          ELIXIR_VERSION: 1.8.2-otp-22
          LC_ALL: C.UTF-8
    <<: *defaults
    steps:
      - checkout
      - <<: *install_system_deps
      - <<: *install_elixir
      - <<: *install_hex_rebar
      - run: mix deps.get
      - run: mix compile
      - run: mix test

  build_example_elixir_1_9_otp_22:
    docker:
      - image: nervesproject/nerves_system_br:1.8.5
        environment:
          MIX_TARGET: rpi0
          ELIXIR_VERSION: 1.9.1-otp-22
          LC_ALL: C.UTF-8
    <<: *defaults
    steps:
      - checkout
      - <<: *install_elixir
      - <<: *install_hex_rebar
      - <<: *install_nerves_bootstrap
      - restore_cache:
          keys:
            - v1-example-mix-cache-{{ checksum "mix.lock" }}
      - run: mkdir -p ~/.ssh && touch ~/.ssh/id_rsa.pub
      - run: cd example && mix deps.get
      - run: cd example && mix firmware
      - run: cd example && mix format --check-formatted
      - run: cd example && mix dialyzer --halt-exit-status
      - save_cache:
          key: v1-example-mix-cache-{{ checksum "mix.lock" }}
          paths:
            - example/_build
            - example/deps

workflows:
  version: 2
  build_test:
    jobs:
      - build_elixir_1_9_otp_22
      - build_elixir_1_8_otp_22
      - build_example_elixir_1_9_otp_22
